### ISSUE TITLE
Deploy to WeDeploy

### ISSUE THREAD

**Issue by thektan** [thektan/taste#5]
- [x] Create project on WeDeploy
- [x] Setup project on WeDeploy
- [x] Deploy to WeDeploy

**Comment by thektan** [comment]
@kienD Did you just need to change the port to get it to successfully deploy?

**Comment by kienD** [comment]
@thektan Yeah, I had to set the environment variable to 80 to get it to be accessible on wedeploy since I set the default port to 8080 for development environments.
